name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login to DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Build Docker Image
      - name: Build Image
        run: docker build -t sanketamte123/sanket-app:v1 .

      # 4. Push Image
      - name: Push Image
        run: docker push sanketamte123/sanket-app:v1
